version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "8082:8082"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  backend:
    build: ./server
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      - ./server/data:/app/data
